### PR TITLE
developer-guide: Add "how to make a release ?" section

### PR DESCRIPTION
**Pull request by jcfr**
Fixes https://github.com/QIICR/dcmqi/issues/324

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @fedorov

**Comment by fedorov** [comment]
👍 

Just one question - do we want to keep the rule that releases will have odd numbers? There is a reference about this in the cmake file. I am not sure this is needed - we follow semantic versioning, and I don't think it is so common to have odd/even distinction for releases. What do you think?

**Comment by jcfr** [comment]
> do we want to keep the rule that releases will have odd numbers?

This is most likely a left over from copy/paste.

I which file did you see this ?

**Comment by fedorov** [comment]
Hmmm .. I can't find where I saw this ... I will let you know if I find it.

**Comment by fedorov** [comment]
FYI to remove redundancy, I integrated this content into this page: https://qiicr.gitbooks.io/dcmqi-guide/content/developer-guide/github-release-generation.html

**Comment by jcfr** [comment]
Makes sense.

**Pull request merged**
